# Generated by Django 5.0.4 on 2026-06-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=200)),
                ('google_drive_folder_id', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('pending_validation', 'Aguardando validação')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.city')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-event_date'],
            },
        ),
    ]
