# Generated by Django 5.0.4 on 2026-06-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='drive_upload_folder_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=200)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200)),
                ('web_view_link', models.URLField(blank=True, max_length=1000)),
                ('original_filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('hash_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Enviado'), ('selected_for_edit', 'Em edição'), ('pending_review', 'Aguardando revisão'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('rejected_final', 'Rejeitado')], default='uploaded', max_length=30)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='core.event')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('drive_file_id', models.CharField(max_length=200)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('original', 'Original'), ('edited', 'Editada'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='original', max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_versions', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.media')),
            ],
            options={
                'verbose_name': 'Versão de Mídia',
                'verbose_name_plural': 'Versões de Mídia',
                'ordering': ['media', 'version'],
                'unique_together': {('media', 'version')},
            },
        ),
    ]
