# Generated by Django 5.0.4 on 2026-06-19 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_media_mediaversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('editor', 'Editor'), ('curator', 'Curador'), ('publisher', 'Publicador')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('abandoned', 'Abandonada')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('deletion_reason_type', models.CharField(blank=True, choices=[('technical_issue', 'Problema técnico'), ('wrong_file', 'Arquivo errado'), ('duplicate', 'Arquivo duplicado'), ('client_request', 'Pedido do cliente'), ('other', 'Outro')], max_length=30)),
                ('deletion_reason_custom', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abandoned_tasks', to=settings.AUTH_USER_MODEL)),
                ('media_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.mediaversion')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Aprovado'), ('rejected_with_return', 'Rejeitado com retorno'), ('rejected_final', 'Rejeitado definitivamente')], max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_history', to='core.media')),
                ('media_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_history', to='core.mediaversion')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Tarefa',
                'verbose_name_plural': 'Histórico de Tarefas',
                'ordering': ['-created_at'],
            },
        ),
    ]
