# Generated by Django 5.0.4 on 2026-06-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_taskhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDriveDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=200)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('deleted', 'Deletado'), ('failed_max_attempts', 'Falha máxima')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_deletions', to='core.mediaversion')),
            ],
            options={
                'verbose_name': 'Deleção Pendente',
                'verbose_name_plural': 'Deleções Pendentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
