# Generated by Django 5.0.4 on 2026-06-19 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pending_drive_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('partial', 'Parcial'), ('failed', 'Falha')], max_length=20)),
                ('events_processed', models.PositiveIntegerField(default=0)),
                ('events_failed', models.PositiveIntegerField(default=0)),
                ('error_traceback', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Script',
                'verbose_name_plural': 'Logs de Script',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('uploaded', 'Upload'), ('selected', 'Selecionado'), ('submitted', 'Enviado para revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('published', 'Publicado'), ('abandoned', 'Desistência'), ('fraud_attempt', 'Tentativa de fraude'), ('calendar_sync_created', 'Sync: evento criado'), ('calendar_sync_updated', 'Sync: evento atualizado'), ('calendar_sync_cancelled', 'Sync: evento cancelado')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'ordering': ['-created_at'],
            },
        ),
    ]
