# Generated by Django 5.0.4 on 2026-06-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mediaversion_cloudinary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Task anterior que originou esta (cadeia de iterações após rejeição com retorno).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tasks', to='core.task'),
        ),
    ]
