# Generated by Django 5.0.4 on 2026-06-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCloudinaryUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('uploaded', 'Enviado'), ('failed_max_attempts', 'Falha máxima')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_cloudinary', to='core.media')),
                ('media_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_cloudinary', to='core.mediaversion')),
            ],
            options={
                'verbose_name': 'Upload Cloudinary Pendente',
                'verbose_name_plural': 'Uploads Cloudinary Pendentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
