# Generated by Django 5.0.4 on 2026-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pendingcloudinaryupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('uploaded', 'Upload'), ('deleted', 'Removido'), ('selected', 'Selecionado'), ('submitted', 'Enviado para revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('published', 'Publicado'), ('abandoned', 'Desistência'), ('fraud_attempt', 'Tentativa de fraude'), ('calendar_sync_created', 'Sync: evento criado'), ('calendar_sync_updated', 'Sync: evento atualizado'), ('calendar_sync_cancelled', 'Sync: evento cancelado')], max_length=50),
        ),
    ]
