# Generated by Django 5.0.4 on 2026-06-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='perceptual_hash',
            field=models.CharField(blank=True, help_text='dHash 256-bit (hex, 64 chars) da versão original (identificação visual sem EXIF)', max_length=64, null=True),
        ),
    ]
